// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "xyz-finance-api/internal/transaction/domain"

	mock "github.com/stretchr/testify/mock"
)

// TransactionCommandRepositoryInterface is an autogenerated mock type for the TransactionCommandRepositoryInterface type
type TransactionCommandRepositoryInterface struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: user
func (_m *TransactionCommandRepositoryInterface) CreateTransaction(user domain.Transaction) (domain.Transaction, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Transaction) (domain.Transaction, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.Transaction) domain.Transaction); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(domain.Transaction) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionCommandRepositoryInterface creates a new instance of TransactionCommandRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionCommandRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionCommandRepositoryInterface {
	mock := &TransactionCommandRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
